docs: add initial release-process.md
ansible-community/ansible-build-data pull request #227
Opened 2023-05-06 21:02 UTC by gotmax23

2023-05-06 21:07 UTC, gotmax23 commented
@anweshadas (and anyone else who has done the releases in the past that feels like chiming in) , I'd really appreciate your opinion here :smile:. Am I missing anything important? Is there anything that you do differently? Is there anything that's incorrect?

Also I'd appreciate more information about the release announcements (step `#8`). I'm not sure where the the Matrix template comes from.

2023-05-07 14:16 UTC, felixfontein commented
CC @rooftopcellist

2023-05-10 15:08 UTC, anweshadas commented
I am working on this. Will be sharing this by this week.

2023-05-15 16:39 UTC, gotmax23 commented on docs/release-process.md
> +
Why does the release need to be done inside of a container?

2023-05-15 16:39 UTC, gotmax23 commented on docs/release-process.md
> +   ```
Where does this key come from? Do all release managers have a copy of it?

2023-05-15 16:41 UTC, gotmax23 commented
Thanks for the review @anweshadas! I left some follow up comments.

2023-05-16 13:21 UTC, anweshadas commented on docs/release-process.md
> +   ```
Currently it is with the Red Hat.

2023-05-16 17:17 UTC, anweshadas commented on docs/release-process.md
> +
For having a clean build environment, which is  also better for standard security ideas.

2023-05-16 17:20 UTC, anweshadas commented on docs/release-process.md
> +
We created a template for the announcement templates. We need to figure out a place to publish it. @gotmax23 can you suggest something?

2023-05-17 12:04 UTC, felixfontein commented on docs/release-process.md
> +
I would put the template(s) in this repository as well (maybe some subdirectory of `docs/`, like `docs/templates/`?). That way it's also easier for folks to suggest improvements to the templates (by creating a PR).

2023-05-20 02:57 UTC, gotmax23 commented on docs/release-process.md
> +
I agree with @felixfontein that this repo is a good place to publish the announcement templates. I think a `docs/announcements` or maybe just a separate folder at the repo root would work.

2023-05-24 18:20 UTC, gotmax23 commented on docs/release-process.md
> +
See the latest commit.

2023-05-24 18:23 UTC, gotmax23 commented on docs/release-process.md
> +   ```
I think this is now a moot point. See https://blog.pypi.org/posts/2023-05-23-removing-pgp/.

/resolve

2023-05-24 18:28 UTC, gotmax23 commented
Triggering CI

2023-06-28 04:48 UTC, felixfontein reviewed
The ansible docsite is now part of ansible/ansible-documentation.

2023-06-28 04:48 UTC, felixfontein commented on docs/release-process.md
> +2. Checkout the antsibull and ansible/ansible (ansible-core) repositories
```suggestion
2. Checkout the antsibull and ansible/ansible-documentation repositories
```

2023-06-28 04:48 UTC, felixfontein commented on docs/release-process.md
> +   git clone https://github.com/ansible/ansible
```suggestion
   git clone https://github.com/ansible/ansible-documentation
```

2023-06-28 04:48 UTC, felixfontein commented on docs/release-process.md
> +5. Submit a PR to ansible/ansible to add the new porting guide to the docsite.
```suggestion
5. Submit a PR to ansible/ansible-documentation to add the new porting guide to the docsite.
```

2023-06-28 04:49 UTC, felixfontein commented on docs/release-process.md
> +5. Submit a PR to ansible/ansible to add the new porting guide to the docsite.
@oraNod @samccann is this ready for updating the release process accordingly?

2023-07-13 08:22 UTC, anweshadas requested changes
Apart from those few small changes everything looks good.

2023-07-13 08:22 UTC, anweshadas commented on docs/release-process.md
> +   pip install -U pip
`python3 -m pip install -U pip`

2023-07-13 08:22 UTC, anweshadas commented on docs/release-process.md
> +   pip install antsibull ansible-core twine
`python3 -m pip install antsibull ansible-core twine`

2023-07-13 13:49 UTC, anweshadas commented
Created the PR https://github.com/ansible-community/ansible-build-data/pull/258 for the  announcement templates.

2023-07-13 15:45 UTC, merged